services:
  spotify-secrets-grabber:
    image: misiektoja/spotify-secrets-grabber:latest
    pull_policy: always
    working_dir: /work
    # SELinux (Fedora/RHEL): change to ".:/work:Z"
    volumes:
      - .:/work
    shm_size: 1g
